# This file was generated by nvfetcher, please do not modify it manually.
# Run `nix run .#update -- -c nvfetcher.toml -o _sources.nix` to regenerate.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  kv-cli = {
    pname = "kv-cli";
    version = "0.1.e6860f0";
    src = fetchurl {
      url = "https://github.com/KUKARAF/kv_cli/releases/download/0.1.e6860f0/kv-linux-amd64.tar.gz";
      sha256 = "sha256-NO/sjErIpqOaHne4WvAJHmT7d+xPFFGo1+GlWWkWuJE=";
    };
  };
}
