# This file was generated by nvfetcher, please do not modify it manually.
# Run `nix run .#update -- -c nvfetcher.toml` to regenerate.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gogcli = {
    pname = "gogcli";
    version = "0.11.0";
    src = fetchurl {
      url = "https://github.com/steipete/gogcli/releases/download/v0.11.0/gogcli_0.11.0_linux_amd64.tar.gz";
      sha256 = "sha256-ypi6VuKczTcT/nv4Nf3KAK4bl83LewvF45Pn7bQInIQ=";
    };
  };
  kv-cli = {
    pname = "kv-cli";
    version = "0.1.e6860f0";
    src = fetchurl {
      url = "https://github.com/KUKARAF/kv_cli/releases/download/0.1.e6860f0/kv-linux-amd64.tar.gz";
      sha256 = "sha256-NO/sjErIpqOaHne4WvAJHmT7d+xPFFGo1+GlWWkWuJE=";
    };
  };
}
