[kv-cli]
src.github = "KUKARAF/kv_cli"
fetch.url = "https://github.com/KUKARAF/kv_cli/releases/download/$ver/kv-linux-amd64.tar.gz"

[debrid-collector]
src.github = "KUKARAF/debrid_collector"
fetch.url = "https://github.com/KUKARAF/debrid_collector/releases/download/$ver/debrid-collector-linux-amd64.tar.gz"
