[kv-cli]
src.github = "KUKARAF/kv_cli"
fetch.url = "https://github.com/KUKARAF/kv_cli/releases/download/$ver/kv-linux-amd64.tar.gz"

[debrid-collector]
src.github = "KUKARAF/debrid_collector"
fetch.url = "https://github.com/KUKARAF/debrid_collector/releases/download/$ver/debrid-collector-linux-amd64.tar.gz"

[sheets]
src.github = "maaslalani/sheets"
fetch.url = "https://github.com/maaslalani/sheets/releases/download/$ver/sheets_Linux_x86_64.tar.gz"

[lazyjira]
src.github = "textfuel/lazyjira"
fetch.url = "https://github.com/textfuel/lazyjira/releases/download/$ver/lazyjira_linux_amd64.tar.gz"
