[kv-cli]
src.github = "KUKARAF/kv_cli"
fetch.url = "https://github.com/KUKARAF/kv_cli/releases/download/$ver/kv-linux-amd64.tar.gz"

[gogcli]
src.website.url = "https://api.github.com/repos/steipete/gogcli/releases/latest"
src.website.regex = "\"tag_name\": \"v([^\"]+)\""
fetch.url = "https://github.com/steipete/gogcli/releases/download/v$ver/gogcli_$ver_linux_amd64.tar.gz"
