# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  debrid-collector = {
    pname = "debrid-collector";
    version = "0.1.8ebe9f7";
    src = fetchurl {
      url = "https://github.com/KUKARAF/debrid_collector/releases/download/0.1.8ebe9f7/debrid-collector-linux-amd64.tar.gz";
      sha256 = "sha256-hEM5uBdx0VhZJY9Jbg3x+YMHavUoggD+aGLYFSQLUKo=";
    };
  };
  kv-cli = {
    pname = "kv-cli";
    version = "0.1.23b7b81";
    src = fetchurl {
      url = "https://github.com/KUKARAF/kv_cli/releases/download/0.1.23b7b81/kv-linux-amd64.tar.gz";
      sha256 = "sha256-AwgNKvnBN6gvpGh7EbTSfRWMIBBg6qJIeW0FrRZooZ8=";
    };
  };
  lazyjira = {
    pname = "lazyjira";
    version = "v2.15.0";
    src = fetchurl {
      url = "https://github.com/textfuel/lazyjira/releases/download/v2.15.0/lazyjira_linux_amd64.tar.gz";
      sha256 = "sha256-S/aTsQHkptfOIY5/CAeGKz3DSEm9n57TrEuKgsEbPBw=";
    };
  };
  pastel = {
    pname = "pastel";
    version = "v0.12.0";
    src = fetchurl {
      url = "https://github.com/sharkdp/pastel/releases/download/v0.12.0/pastel-v0.12.0-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-csodtJaWcBpT/Yot/0yLFnwxwaxPpay9G6j8Bi0bHj4=";
    };
  };
  sheets = {
    pname = "sheets";
    version = "v0.2.0";
    src = fetchurl {
      url = "https://github.com/maaslalani/sheets/releases/download/v0.2.0/sheets_Linux_x86_64.tar.gz";
      sha256 = "sha256-WGjRYqLfR3HNNhIq6OYIynr8o9OHdLLRfpcn24FunGk=";
    };
  };
}
