# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  debrid-collector = {
    pname = "debrid-collector";
    version = "0.1.73753ed";
    src = fetchurl {
      url = "https://github.com/KUKARAF/debrid_collector/releases/download/0.1.73753ed/debrid-collector-linux-amd64.tar.gz";
      sha256 = "sha256-igTENFmo3hhE9tZ7gqywFtGr82+IMwPPjNnkH0+6bRw=";
    };
  };
  kv-cli = {
    pname = "kv-cli";
    version = "0.1.c99e9fb";
    src = fetchurl {
      url = "https://github.com/KUKARAF/kv_cli/releases/download/0.1.c99e9fb/kv-linux-amd64.tar.gz";
      sha256 = "sha256-1Ng54lFbATY2Kqi75dD5jhziREkNXs1cT4OgtdH/79o=";
    };
  };
  lazyjira = {
    pname = "lazyjira";
    version = "v2.10.1";
    src = fetchurl {
      url = "https://github.com/textfuel/lazyjira/releases/download/v2.10.1/lazyjira_linux_amd64.tar.gz";
      sha256 = "sha256-2ouVPnmZ1koZ0mnQSyHpfO5jR9IspKjBZYkn28F9lII=";
    };
  };
  sheets = {
    pname = "sheets";
    version = "v0.2.0";
    src = fetchurl {
      url = "https://github.com/maaslalani/sheets/releases/download/v0.2.0/sheets_Linux_x86_64.tar.gz";
      sha256 = "sha256-WGjRYqLfR3HNNhIq6OYIynr8o9OHdLLRfpcn24FunGk=";
    };
  };
}
