# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  debrid-collector = {
    pname = "debrid-collector";
    version = "0.1.8ebe9f7";
    src = fetchurl {
      url = "https://github.com/KUKARAF/debrid_collector/releases/download/0.1.8ebe9f7/debrid-collector-linux-amd64.tar.gz";
      sha256 = "sha256-hEM5uBdx0VhZJY9Jbg3x+YMHavUoggD+aGLYFSQLUKo=";
    };
  };
  kv-cli = {
    pname = "kv-cli";
    version = "0.1.a567059";
    src = fetchurl {
      url = "https://github.com/KUKARAF/kv_cli/releases/download/0.1.a567059/kv-linux-amd64.tar.gz";
      sha256 = "sha256-iQ6CUhe+3ktu0OXtojROhYmIcHDvV9hD9XUWF9uNDxo=";
    };
  };
  lazyjira = {
    pname = "lazyjira";
    version = "v2.19.2";
    src = fetchurl {
      url = "https://github.com/textfuel/lazyjira/releases/download/v2.19.2/lazyjira_linux_amd64.tar.gz";
      sha256 = "sha256-UDtOJvRpeW2hH62++Xmgsu3g17rWPDvDTtbeeza3IUw=";
    };
  };
  pastel = {
    pname = "pastel";
    version = "v0.12.0";
    src = fetchurl {
      url = "https://github.com/sharkdp/pastel/releases/download/v0.12.0/pastel-v0.12.0-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-csodtJaWcBpT/Yot/0yLFnwxwaxPpay9G6j8Bi0bHj4=";
    };
  };
  sheets = {
    pname = "sheets";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/maaslalani/sheets/releases/download/v0.3.0/sheets_Linux_x86_64.tar.gz";
      sha256 = "sha256-JDablY3nmYmDLaScwlvwD6+w9b8BGXYeo9u7+ip17a8=";
    };
  };
}
